### ISSUE TITLE
Cleanup the Access console

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#101]
Just keep Welcome to the opeNode Terminal

Then just have a prompt: opeNode $ ____

when the use type something and press enter, call a route in the Admin::InstanceAccessController

**Comment by martinlevesque** [comment]
Many issues:

- remove Type "help" to get a supporting command list.
- remove the success
- give an example command result without "success" thing, it should look like a regular shell
- remove opeNode in the command prompt
![image](https://user-images.githubusercontent.com/8007722/75614100-3b87b380-5b03-11ea-8984-77ad26e8ca50.png)

the console is buggy when you type multiple commands - it becomes unresponsible

**Comment by martinlevesque** [comment]
Issues:

- there are errors in the console "TypeError: Cannot read property 'current_path' of undefined
    at ls (openode_terminal.js:16)
    at VueComponent._callee2$ (vue-command.common.js:4177)"

- when the user type and press enter, it should call a controller action with the command

**Comment by martinlevesque** [comment]
remaining:

- when the user type and press enter, it should call a controller action with the command

**Comment by gastonsoto** [comment]
Commands entered here, need to be defined in the terminal Vue controller.
Maybe I can make any command call the same method. Will check.

**Comment by gastonsoto** [comment]
Ok, each command needs to be defined as method in the Vue controller. Commands are calling controllers now.

**Comment by martinlevesque** [comment]
In the following image

![image](https://user-images.githubusercontent.com/8007722/75880935-3de05b00-5dec-11ea-94d4-1e24bf90a6a4.png)

It should have call POST /admin/instances/instance-id/access/cmd, { cmd: "adsfasdf" }

and

POST /admin/instances/instance-id/access/cmd, { cmd: "asdfasdfsadf" }

/admin/instances/instance-id/access/cmd action should be json based, so the view will get command result and print it.

**Comment by gastonsoto** [comment]
Ok, update the URL to get the command response. You have to still define each available command in the component. Example:

```
        cd: ({ _ }) => {          
          const self = this         

          return new Promise(resolve => {
            axios.get(self.url, { cmd: `"${_.join(' ')}"`})
            .then(response => {            
              self.current_path = _[1]
              resolve(response.data.msg)
            })          
            .catch(err => {
              resolve(err.response.data);
            })
          })
        } 
```

**Comment by martinlevesque** [comment]
I however do not want to define cmds, the user can type anything. The command is any string.

**Comment by martinlevesque** [comment]
2 issues:

- if I type the command df -h -h, the parameter cmd is "df"
- unable to copy the content in the console

**Comment by gastonsoto** [comment]
Fixing the params. I'm being able to copy and paste. Can you record a short video so I can see the issue?

**Comment by gastonsoto** [comment]
Done.

**Comment by martinlevesque** [comment]
looks now good, please change the GET into a POST when we press enter on the command line
