### ISSUE TITLE
Access logs should take 100% height

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#102]
Currently it's only half

**Comment by gastonsoto** [comment]
Logs moved to "Console". Users should be able to do:

$ logs n

To return "n" lines of latest logs. More parameters can be configured to the be passed to the task.

**Comment by martinlevesque** [comment]
note that the console is not an interface for the CLI, it allows to run commands in a container (or you can think it's a linux shell like bash), so you can run any command like "ls"
