### ISSUE TITLE
Admin - billing - make a payment

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#105]
Via paypal:
![image](https://user-images.githubusercontent.com/8007722/75380598-4f35de80-58a5-11ea-9a79-809614c356a1.png)

With cryptocurrency (bitcoin, bitcoin cash, ether)

![image](https://user-images.githubusercontent.com/8007722/75380693-7c828c80-58a5-11ea-99b4-9e0c1cfcca8a.png)

**Comment by gastonsoto** [comment]
![Screen Shot 2020-03-01 at 03 05 27](https://user-images.githubusercontent.com/786208/75620610-90f6ab80-5b69-11ea-94b3-3c24f0b5bd14.png)
