### ISSUE TITLE
Admin instances, add a "tips" area, maybe with something like exclamation mark

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#107]
![image](https://user-images.githubusercontent.com/8007722/75386756-38e15000-58b0-11ea-9e20-1f67e5479c35.png)

**Comment by martinlevesque** [comment]
not done

**Comment by gastonsoto** [comment]
My bad, I did this globally for any page. If @tips is present, a div will show up at the top. See:

```
  def index
    @tips = "This is the instances page, where you can see your instances."

    respond_to do |format|
      format.html
      format.json { render json: instances_summary }
    end
  end
```

![Screen Shot 2020-02-29 at 18 09 59](https://user-images.githubusercontent.com/786208/75615121-b9a58380-5b1e-11ea-9f46-a4343358d0e7.png)
