### ISSUE TITLE
Adapt the admin instances page for new users

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#108]
When the user first register, add something big in the middle, like "add your first site >>", with a button doing the same thing as "Add new"

![image](https://user-images.githubusercontent.com/8007722/75388068-56171e00-58b2-11ea-9e24-6b181a756371.png)

**Comment by martinlevesque** [comment]
it's not done. add "No website yet, get started. Add new"

**Comment by gastonsoto** [comment]
It's done, check the instances component. When instance length is zero, you
see an image and button to create the first one.

**Comment by martinlevesque** [comment]
mm that's what I get

![image](https://user-images.githubusercontent.com/8007722/75614131-a20cd180-5b03-11ea-9a7d-969ada41ddd7.png)

**Comment by gastonsoto** [comment]
weird - I'll check it out

**Comment by gastonsoto** [comment]
Fixed. Will be in the next push.

![Screen Shot 2020-03-01 at 01 35 51](https://user-images.githubusercontent.com/786208/75619612-2b9cbd80-5b5d-11ea-90b7-4e03947d3af9.png)

**Comment by martinlevesque** [comment]
nice!
