### ISSUE TITLE
persistence page issues

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#116]
![image](https://user-images.githubusercontent.com/8007722/75629371-9971d500-5baf-11ea-9f98-539e36d7d565.png)

**Comment by martinlevesque** [comment]
![image](https://user-images.githubusercontent.com/8007722/75629398-d9d15300-5baf-11ea-8b4d-bbc6b315f452.png)

**Comment by martinlevesque** [comment]
issues are still the same

**Comment by martinlevesque** [comment]
missing save button for Persistence size (GB)

**Comment by gastonsoto** [comment]
Done!
