### ISSUE TITLE
angular icon appears in the browser title

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#143]

**Comment by gastonsoto** [comment]
Pushed a little update. But I don't see the angular icon on the admin browser title:

![Screen Shot 2020-03-08 at 08 45 56](https://user-images.githubusercontent.com/786208/76162152-77c99e00-6119-11ea-8355-7d3bb9edbfc6.png)

**Comment by martinlevesque** [comment]
Its only happening sometimes on random pages

**Comment by martinlevesque** [comment]
mm i don't seem to be able to see it on https://wwwtest.openode.io/ in production mode, maybe only happen in development, will close it and reopen if i see it in prod environment
