### ISSUE TITLE
in change plan, when the project is already open source, the open source form do not show

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#144]
![image](https://user-images.githubusercontent.com/8007722/76488727-9f13ba00-63fc-11ea-9480-9ac84e5e548f.png)

check also in the Add site

**Comment by gastonsoto** [comment]
Should be fixed.

**Comment by martinlevesque** [comment]
when you switch back to other than open source it should not keep the open source fields

![image](https://user-images.githubusercontent.com/8007722/76621904-c9ea3500-6506-11ea-9ac9-3feb55258448.png)
