### ISSUE TITLE
Ability to start and restart instance from dashboard.

### ISSUE THREAD

**Issue by RamonRobben** [openode-io/openode-www#202]
I'm not sure if this is still hidden somewhere on the page but I recall I could start and restart an instance in the previous version of opeNode. I kinda miss this feature and it would be nice if it could be implemented again.

Maybe the buttons for starting / stopping or restarting could be above the delete button.

**Comment by martinlevesque** [comment]
Hi there,

Thanks for your feedback! 

You can kinda do it from the dashboard, if you go to Access > Deployments. When the button "Rollback" is present it means you can redeploy with this image. 

I agree it would be convenient to have a Restart from the main screen which takes the latest available image and basically do a rollback.

**Comment by martinlevesque** [comment]
It's now available @RamonRobben , let us know if you have any comment.
