### ISSUE TITLE
Improve error message on "no available deployment" 

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#247]
specify to use the cli

**Comment by KimPlayz4LK** [comment]
It says 'No available execution'

**Comment by KimPlayz4LK** [comment]
![image](https://user-images.githubusercontent.com/49796402/94362263-86b17700-0090-11eb-8def-632e238e78bd.png)

**Comment by martinlevesque** [comment]
@KimPlayz4LK it means you should deploy using the CLI as there is no latest image available.

**Comment by martinlevesque** [comment]
The error msg will now look like:

![image](https://user-images.githubusercontent.com/8007722/94367323-e8cba580-00ab-11eb-88c3-bda3e27aadee.png)

and the title the of button (Deploy) will be Deploy Latest

**Comment by KimPlayz4LK** [comment]
Can we host endless servers?

**Comment by KimPlayz4LK** [comment]
@martinlevesque Can we host endless servers?

**Comment by martinlevesque** [comment]
> Can we host endless servers?

Can you provide more details what endless servers are?
