### ISSUE TITLE
Resources usage problems

### ISSUE THREAD

**Issue by Zerotask** [openode-io/openode-www#318]
There are no data available. I don't know if there is a monthly reset or so, but this should be avoided. There is also a **null** which seems like a bug.
Last month I saw some data there.

![image](https://user-images.githubusercontent.com/20150243/116780010-fdc14a80-aa79-11eb-8004-53edd18f9f2a.png)

**Comment by martinlevesque** [comment]
Thanks for the issue report.
Could you specify which site id is having the missing data, if you click on Access / Deploy, then resource:

https://www.openode.io/admin/instances/<WEBSITE_ID>/access/resources_usage

What is the ID?

Thanks

**Comment by Zerotask** [comment]
The ID is 28225

**Comment by martinlevesque** [comment]
should filter stats list containing null

**Comment by martinlevesque** [comment]
The issue has been fixed
