### ISSUE TITLE
Text is hard to read

### ISSUE THREAD

**Issue by Zerotask** [openode-io/openode-www#331]
![image](https://user-images.githubusercontent.com/20150243/131213240-9e8a6c11-cc2d-48cb-bbb1-60dfbc567e5d.png)
https://www.openode.io/admin/instances

For comparison reasons, I changed the color of the last item to `#000;`

I noticed this on other pages as well, for example on the Deployments page.

**Comment by martinlevesque** [comment]
Thanks for the report. On recent chrome browsers normally the text should look like almost black, not light grey.

Which browser and version are you using?

**Comment by Zerotask** [comment]
I'm using the latest Brave browser which uses Chromium 92.x as far as I know.

**Comment by martinlevesque** [comment]
Just tested with the latest Brave on Ubuntu:

`Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit)
`

There is no color issue with that version. @Zerotask  please try to upgrade to the latest.

**Comment by Zerotask** [comment]
It seems that it is fixed now.
