### ISSUE TITLE
Admin - documentation icon

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#70]
In the layout, have a "documentation" icon when there is documentation, it would link to the proper /docs/document.md. This icon could be enabled when there is for example @doc_link (or whatever variable) set from the controller or something like that

In this way the user can quickly find the right documentation depending on where he is

**Comment by gastonsoto** [comment]
Example on:

/admin/instances/1/collaborators

**Comment by martinlevesque** [comment]
the icon is correct, however it should be in the layout somewhere in a corner. This is something global in admin, not page specific

**Comment by martinlevesque** [comment]
still the same, it should be in the layout, not page specific

**Comment by gastonsoto** [comment]
Adding to the header, to the left of the bell icon.
