### ISSUE TITLE
Admin - On notification bell dropdown click, should update viewed

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#76]
should call /notifications/mark_viewed with the list of notification ids (maximum 5)

see commit https://github.com/openode-io/openode-www/commit/fb1fe553bf1db48eeed620757224dd4d175b470b

**Comment by martinlevesque** [comment]
no request is done

**Comment by martinlevesque** [comment]
good, however the mark_read makes errors;

error: "ActionController::InvalidAuthenticityToken"

**Comment by gastonsoto** [comment]
mmm yeh that's on the controller, probably skiping the auth is not working.
Will check
