### ISSUE TITLE
Admin instances home, quick action menu hover is not visible

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#84]
When you hover in this dropdown, it's not visible as other dropdown (make sure to be consistent)

![image](https://user-images.githubusercontent.com/8007722/73993534-69bd0d80-4920-11ea-9a3b-ca5507f34301.png)

**Comment by martinlevesque** [comment]
still the same issue

**Comment by gastonsoto** [comment]
Ok I now see what you mean, the background color on hover is different. Will fix.
