### ISSUE TITLE
Number unread should be coming from the API

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#85]
If you see in notifications list component, I changed

      axios.get('/admin/notifications')
this returns:
{ notifications: [list of notifications], nb_unviewed: n }

![image](https://user-images.githubusercontent.com/8007722/73993573-940ecb00-4920-11ea-9d20-37266dc3454e.png)

So the number "2" should take it from ['nb_unviewed']

When you click on the notification, don't remove it, it's weird.

When you open the list of notifications, it should mark them all as read

**Comment by gastonsoto** [comment]
Changed to just a red dot. Reduce potential issues, plus I think it looks cleaner. When notifications are available the red dot shows up.

**Comment by martinlevesque** [comment]
does not work. when you view the notifications, it keeps having the red bubble - should not be visible when there is nothing new.

**Comment by gastonsoto** [comment]
![opeNode_notifications_buble](https://user-images.githubusercontent.com/786208/75614802-32a2dc00-5b1b-11ea-9f99-a7ac3f26ba53.gif)

**Comment by martinlevesque** [comment]
ah i see. I must say it seems weird. would be better I think that on dropdown load we can assume things are read and so can mark them all as read by passing the list of notification ids

**Comment by martinlevesque** [comment]
still the same. It should call mark read with the list of id, and also no action when you click on a notification

**Comment by gastonsoto** [comment]
On every notification click, a request is made to mark that notification as read (right now I'm getting error 400 on that request). Maybe instead of marking read on notification click, we put a little "Mark Read" button?

**Comment by martinlevesque** [comment]
i personnally prefer to mark them all on dropdown load. but adding a button could help

**Comment by gastonsoto** [comment]
On bell click each item fires markRead, but items are kept in the list. If those items are clicked, they will dissapear.
