### ISSUE TITLE
Errors in website create are not propagated from the api and displayed red

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-www#89]
In instances controller, on instance create ( api(:post, '/instances/create', payload: instance_params) ), if it throws an error, it should be shown in red

Also you are kind of stuck in the form (keep on "Creating...") - you should be able to fix and then click create again. Make sure that it works in future forms also

![image](https://user-images.githubusercontent.com/8007722/74088637-7a779b80-4a66-11ea-9969-8ad9a2fcb9de.png)

**Comment by martinlevesque** [comment]
now propagated, but it should appear red

![image](https://user-images.githubusercontent.com/8007722/75613918-d763f000-5b00-11ea-9661-be1fb47cf343.png)

**Comment by martinlevesque** [comment]
they are still yellow

**Comment by gastonsoto** [comment]
Is level coming in the response?

**Comment by martinlevesque** [comment]
if the status code is not 200 it means it's an error
